/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface NiCopyright {
    'items': any;
    'title': string;
  }
  interface NiFooter {}
  interface NiGlobalCss {}
}

declare global {


  interface HTMLNiCopyrightElement extends Components.NiCopyright, HTMLStencilElement {}
  var HTMLNiCopyrightElement: {
    prototype: HTMLNiCopyrightElement;
    new (): HTMLNiCopyrightElement;
  };

  interface HTMLNiFooterElement extends Components.NiFooter, HTMLStencilElement {}
  var HTMLNiFooterElement: {
    prototype: HTMLNiFooterElement;
    new (): HTMLNiFooterElement;
  };

  interface HTMLNiGlobalCssElement extends Components.NiGlobalCss, HTMLStencilElement {}
  var HTMLNiGlobalCssElement: {
    prototype: HTMLNiGlobalCssElement;
    new (): HTMLNiGlobalCssElement;
  };
  interface HTMLElementTagNameMap {
    'ni-copyright': HTMLNiCopyrightElement;
    'ni-footer': HTMLNiFooterElement;
    'ni-global-css': HTMLNiGlobalCssElement;
  }
}

declare namespace LocalJSX {
  interface NiCopyright {
    'items'?: any;
    'title'?: string;
  }
  interface NiFooter {}
  interface NiGlobalCss {}

  interface IntrinsicElements {
    'ni-copyright': NiCopyright;
    'ni-footer': NiFooter;
    'ni-global-css': NiGlobalCss;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'ni-copyright': LocalJSX.NiCopyright & JSXBase.HTMLAttributes<HTMLNiCopyrightElement>;
      'ni-footer': LocalJSX.NiFooter & JSXBase.HTMLAttributes<HTMLNiFooterElement>;
      'ni-global-css': LocalJSX.NiGlobalCss & JSXBase.HTMLAttributes<HTMLNiGlobalCssElement>;
    }
  }
}


