/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface NiEamTest {
    /**
    * The first name
    */
    'first': string;
    /**
    * The last name
    */
    'last': string;
    /**
    * The middle name
    */
    'middle': string;
  }
}

declare global {


  interface HTMLNiEamTestElement extends Components.NiEamTest, HTMLStencilElement {}
  var HTMLNiEamTestElement: {
    prototype: HTMLNiEamTestElement;
    new (): HTMLNiEamTestElement;
  };
  interface HTMLElementTagNameMap {
    'ni-eam-test': HTMLNiEamTestElement;
  }
}

declare namespace LocalJSX {
  interface NiEamTest {
    /**
    * The first name
    */
    'first'?: string;
    /**
    * The last name
    */
    'last'?: string;
    /**
    * The middle name
    */
    'middle'?: string;
  }

  interface IntrinsicElements {
    'ni-eam-test': NiEamTest;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'ni-eam-test': LocalJSX.NiEamTest & JSXBase.HTMLAttributes<HTMLNiEamTestElement>;
    }
  }
}


